# ======= 留空使用default值  ======= #
# ==== 日志相关 ==== #
log:
  console-level:         # default info
  file-level:            # default no log file
  file-path:             # default log/run.log

# ==== 网页相关 ==== #
web:
  domain: example.com:12580   # or example.com:9443 for reserve proxy server
  port:                       # default 12580

# ==== 代理源配置文件 ==== #
source-files:
  # use local file
  - config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# # ==== Postgresql database info ==== #
# database-url: ""

# # ==== TG api info ==== #
# TG-api-url: ""              # default "https://rsshub.v2fy.com/telegram/channel/"

# ==== 爬取设置 ==== #
crawl-interval:             # default 60 (minutes)
healthcheck:
  url:                      # default http://www.gstatic.com/generate_204

#  ==== 获取归属地 ==== #
localcheck:
  url:                      # default https://ip.011102.xyz/ (备选：https://ip.useragentinfo.com/json、http://ip-api.com/json/)
  json-path:                # default IP.Country
  timeout:                  # default 5 (seconds)
  max-conn:                 # default 500. The number of health check connections simultaneously

# ==== 测速 ==== #
speedtest: 
  url:                      # default https://speed.cloudflare.com/__down?bytes=5242880
  is-used: true             # default false. Warning: this will consume large network resources.
  interval:                 # default 720 (min)
  timeout:                  # default 10 (seconds).
  max-conn:                 # default 5. The number of speed test connections simultaneously
