# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        build: [macos, linux, windows]
        include:
          - build: macos
            os: macos-latest
            archive-name: darwin
          - build: linux
            os: ubuntu-latest
            archive-name: linux
          - build: windows
            os: windows-latest
            archive-name: windows

    permissions:
      contents: write
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v -o EasyGetProxy .

    - name: Test
      run: go test -v ./...

    - name: Prepare Packaging
      run: tar zcvf EasyGetProxy_${{ steps.tag_version.outputs.new_tag }}_${{ matrix.archive-name }}.tar.gz EasyGetProxy LICENSE config assets

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EasyGetProxy_${{ steps.tag_version.outputs.new_tag }}_${{ matrix.archive-name }}.tar.gz
        path: EasyGetProxy_${{ steps.tag_version.outputs.new_tag }}_${{ matrix.archive-name }}.tar.gz
      
    - name: Release Version
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: EasyGetProxy_${{ steps.tag_version.outputs.new_tag }}_${{ matrix.archive-name }}.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
