# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*' ]    
  # release:
  #   types: [published]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - uses: fregante/release-with-changelog@v3
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude: '^Ignore|yml|yaml|md|readme|vscode|^Merge'

  build:
    strategy:
      matrix:
        build: [macos, linux, windows]
        include:
          - build: macos
            os: macos-latest
            archive-name: darwin
            exe-name: EasyGetProxy
          - build: linux
            os: ubuntu-latest
            archive-name: linux
            exe-name: EasyGetProxy
          - build: windows
            os: windows-latest
            archive-name: windows
            exe-name: EasyGetProxy.exe

    permissions:
      contents: write
    
    runs-on: ${{ matrix.os }}
    needs: release
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v -o ${{ matrix.exe-name }} .

    - name: Test
      run: go test -v ./...

    - name: Prepare Packaging
      run: tar zcvf EasyGetProxy_${{ github.ref_name }}_${{ matrix.archive-name }}.tar.gz ${{ matrix.exe-name }} LICENSE config assets

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/EasyGetProxy_${{ github.ref_name }}_${{ matrix.archive-name }}.tar.gz
        asset_name: EasyGetProxy_${{ github.ref_name }}_${{ matrix.archive-name }}.tar.gz
        asset_content_type: application/octet-stream